"use client";

import { Printer, X } from "lucide-react";
import * as React from "react";
import { Button } from "@/components/ui/primitives";
import { percent, type Recommendation } from "@/lib/utils";

/**
 * Printable clinical report.
 *
 * Rendered as a normal overlay on screen and as a clean document when printed:
 * `print:` utilities plus the @media print rules in globals.css strip the
 * chrome, so the browser's "Save as PDF" produces the document without any
 * server-side PDF dependency.
 */
export function ReportDocument({
  data,
  onClose,
}: {
  data: Recommendation;
  onClose: () => void;
}) {
  const generated = React.useMemo(
    () =>
      new Date().toLocaleString(undefined, {
        dateStyle: "long",
        timeStyle: "short",
      }),
    [],
  );

  // Escape closes; the overlay is modal so trapping the key here is enough.
  React.useEffect(() => {
    const onKey = (e: KeyboardEvent) => e.key === "Escape" && onClose();
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-label="Clinical report"
      className="fixed inset-0 z-50 overflow-y-auto bg-[rgb(15_23_42_/_0.35)] p-4 print:static print:overflow-visible print:bg-transparent print:p-0"
    >
      <div className="mx-auto max-w-[8.5in] print:max-w-none">
        <div className="mb-3 flex items-center justify-between print:hidden">
          <p className="text-sm text-white/90">
            Use your browser&apos;s print dialog to save this as a PDF.
          </p>
          <div className="flex gap-2">
            <Button variant="secondary" size="sm" onClick={onClose}>
              <X className="h-3.5 w-3.5" />
              Close
            </Button>
            <Button size="sm" onClick={() => window.print()}>
              <Printer className="h-3.5 w-3.5" />
              Print / Save as PDF
            </Button>
          </div>
        </div>

        <article className="rounded-lg bg-white p-10 shadow-2xl print:rounded-none print:p-0 print:shadow-none">
          <header className="border-b-2 border-[var(--accent)] pb-4">
            <div className="flex items-start justify-between gap-6">
              <div>
                <h1 className="text-xl font-bold tracking-tight text-[var(--text)]">
                  Medication Decision Support Report
                </h1>
                <p className="mt-1 text-[13px] text-[var(--text-muted)]">
                  Generated by the Medicine Prescription Engine
                </p>
              </div>
              <div className="text-right text-[11px] leading-relaxed text-[var(--text-muted)]">
                <p>{generated}</p>
                <p className="mt-0.5">Research use only</p>
              </div>
            </div>
          </header>

          <section className="mt-6">
            <h2 className="text-[11px] font-bold uppercase tracking-wider text-[var(--text-subtle)]">
              Presenting description
            </h2>
            <p className="mt-2 border-l-2 border-[var(--border-strong)] pl-3 text-[13px] leading-relaxed text-[var(--text)]">
              {data.query}
            </p>
          </section>

          {data.red_flag && (
            <section className="mt-5 rounded border-2 border-[var(--danger)] bg-[var(--danger-soft)] p-3">
              <h2 className="text-[11px] font-bold uppercase tracking-wider text-[var(--danger)]">
                Urgent — escalation required
              </h2>
              <p className="mt-1.5 text-[13px] leading-relaxed text-[var(--text)]">
                The description mentions{" "}
                <strong>{data.red_flag_terms.join(", ")}</strong>, which can indicate a medical
                emergency requiring immediate assessment.
              </p>
            </section>
          )}

          <section className="mt-6">
            <h2 className="text-[11px] font-bold uppercase tracking-wider text-[var(--text-subtle)]">
              Model assessment
            </h2>
            <table className="mt-2 w-full border-collapse text-[13px]">
              <tbody>
                <tr className="border-b border-[var(--border)]">
                  <td className="py-2 pr-4 font-medium text-[var(--text-muted)]">
                    Most likely condition
                  </td>
                  <td className="py-2 font-semibold text-[var(--text)]">{data.condition}</td>
                  <td className="w-24 py-2 text-right tabular-nums text-[var(--text-muted)]">
                    {percent(data.condition_confidence)}
                  </td>
                </tr>
                {data.alternatives.map((alt) => (
                  <tr key={alt.name} className="border-b border-[var(--border)]">
                    <td className="py-2 pr-4 text-[var(--text-subtle)]">Differential</td>
                    <td className="py-2 text-[var(--text-muted)]">{alt.name}</td>
                    <td className="py-2 text-right tabular-nums text-[var(--text-subtle)]">
                      {percent(alt.score)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>

          <section className="mt-6">
            <h2 className="text-[11px] font-bold uppercase tracking-wider text-[var(--text-subtle)]">
              Associated medications
            </h2>
            <p className="mt-1 text-[11px] italic text-[var(--text-subtle)]">
              Ranked by statistical association in patient-reported data. No dose, route,
              frequency, duration, or interaction check is implied.
            </p>
            <table className="mt-2 w-full border-collapse text-[13px]">
              <thead>
                <tr className="border-b border-[var(--border-strong)] text-left">
                  <th className="w-8 py-1.5 font-semibold text-[var(--text-muted)]">#</th>
                  <th className="py-1.5 font-semibold text-[var(--text-muted)]">Medication</th>
                  <th className="w-28 py-1.5 text-right font-semibold text-[var(--text-muted)]">
                    Association
                  </th>
                </tr>
              </thead>
              <tbody>
                {data.drugs.map((drug, i) => (
                  <tr key={drug.name} className="border-b border-[var(--border)]">
                    <td className="py-2 text-[var(--text-subtle)]">{i + 1}</td>
                    <td className="py-2 font-medium text-[var(--text)]">{drug.name}</td>
                    <td className="py-2 text-right tabular-nums text-[var(--text-muted)]">
                      {percent(drug.score)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>

          <section className="mt-6">
            <h2 className="text-[11px] font-bold uppercase tracking-wider text-[var(--text-subtle)]">
              Supporting evidence
            </h2>
            {data.grounded ? (
              <ol className="mt-2 space-y-3">
                {data.evidence.map((ev, i) => (
                  <li key={ev.chunk_id} className="break-inside-avoid text-[12px]">
                    <p className="font-semibold capitalize text-[var(--text)]">
                      [{i + 1}] {ev.question_focus || ev.document_id}
                      {ev.section && (
                        <span className="font-normal text-[var(--text-muted)]">
                          {" "}
                          — {ev.section.toLowerCase()}
                        </span>
                      )}
                    </p>
                    <blockquote className="mt-1 border-l-2 border-[var(--border-strong)] pl-2.5 leading-relaxed text-[var(--text-muted)]">
                      {ev.text}
                    </blockquote>
                    <p className="mt-1 text-[10px] text-[var(--text-subtle)]">
                      relevance {ev.relevance} · chunk {ev.chunk_id}
                      {ev.source_url && <> · {ev.source_url}</>}
                    </p>
                  </li>
                ))}
              </ol>
            ) : (
              <p className="mt-2 text-[13px] text-[var(--text-muted)]">
                No indexed source passed the relevance threshold. This assessment is
                <strong> unverified</strong> and should be treated as a hypothesis only.
              </p>
            )}
          </section>

          <footer className="mt-8 border-t border-[var(--border-strong)] pt-3">
            <p className="text-[10px] leading-relaxed text-[var(--text-muted)]">
              <strong>Disclaimer.</strong> {data.disclaimer}
            </p>
            <p className="mt-2 text-[10px] text-[var(--text-subtle)]">
              Clinician signature: ______________________________ Date: ______________
            </p>
          </footer>
        </article>
      </div>
    </div>
  );
}
